import './globals.css'
import NavBar from './NavBar'

export const metadata = {
  title: 'Tiendas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  )
}
